### ISSUE TITLE
kaa.beacon.libthumb fails to compile with libpng-1.6

### ISSUE THREAD

**Issue by g1itch** [freevo/kaa-beacon#1]
I installed libpng-1.2, 1.5 and 1.6 but kaa.beacon.libthumb tries to compile with libpng-1.6 and fails. The messages are:

```
building 'kaa.beacon.libthumb' extension
x86_64-pc-linux-gnu-gcc -pthread -fPIC -I/usr/include/libpng16 -I/usr/include/python2.7 -c src/extensions/libthumb.c -o build/temp.linux-x86_64-2.7/src/extensions/libthumb.o -Wall
src/extensions/libthumb.c: In function ‘epeg_thumbnail’:
src/extensions/libthumb.c:103:5: warning: passing argument 2 of ‘_png_write’ discards ‘const’ qualifier from pointer target type [enabled by default]
src/extensions/libthumb.c:54:12: note: expected ‘unsigned int *’ but argument is of type ‘const void *’
src/extensions/libthumb.c: In function ‘initlibthumb’:
src/extensions/libthumb.c:269:15: warning: variable ‘m’ set but not used [-Wunused-but-set-variable]
x86_64-pc-linux-gnu-gcc -pthread -fPIC -I/usr/include/libpng16 -I/usr/include/python2.7 -c src/extensions/libpng.c -o build/temp.linux-x86_64-2.7/src/extensions/libpng.o -Wall
src/extensions/libpng.c: In function ‘_png_write’:
src/extensions/libpng.c:74:11: error: dereferencing pointer to incomplete type
error: command 'x86_64-pc-linux-gnu-gcc' failed with exit status 1
```
